language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=ownbackup
    - BRANCH=master
  matrix:
    - DB=mysql

matrix:
  allow_failures:
    - php: 5.4
    - php: 7
    - php: hhvm
  include:
    - php: 5.5
      env: DB=sqlite
    - php: 5.5
      env: DB=pgsql
    - php: 5.5
      env: "DB=mysql CORE_BRANCH=stable8.1"
    - php: 5.5
      env: "DB=mysql CORE_BRANCH=stable8.2"
  fast_finish: true

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-jinja2 python3-setuptools
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP_NAME

before_script:
  - cd apps/$APP_NAME
  #- composer self-update
  - composer require codeclimate/php-test-reporter --dev

script:
  - phpunit -c phpunit.coverage.xml --coverage-clover build/logs/clover.xml

after_script:
  # report to Code Climate via curl
  # $CODECLIMATE_REPO_TOKEN has to be set as environment variable on travis
  - ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

addons:
    postgresql: "9.3"

notifications:
  email:
    - $NOTIFICATION_EMAIL
